tidy up pre-push hook

diff --git a/dev/git_hooks/pre-push b/dev/git_hooks/pre-push
--- a/dev/git_hooks/pre-push
+++ b/dev/git_hooks/pre-push
@@ -2,31 +2,24 @@
 
 set -Eeuo pipefail
 
-# An example hook script to verify what is about to be pushed.  Called by "git
-# push" after it has checked the remote status, but before anything has been
-# pushed.  If this script exits with a non-zero status nothing will be pushed.
-#
-# This hook is called with the following parameters:
-#
-# $1 -- Name of the remote to which the push is being done
-# $2 -- URL to which the push is being done
-#
-# If pushing without using a named remote those arguments will be equal.
-#
-# Information about the commits which are being pushed is supplied as lines to
-# the standard input in the form:
-#
-#   <local ref> <local oid> <remote ref> <remote oid>
-#
-# This sample shows how to prevent push of commits where the log message starts
-# with "WIP" (work in progress).
+log() { echo >&2 "==> $*"; }
+die() { log "$(bold_red "FATAL: ") $(bold "$*")"; exit 1; }
 
-#remote="$1"
-#url="$2"
+ok() { log "$(bold_green "OK: $*")"; }
 
-#zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')
+styled_text() { ATTR="$1"; shift; echo -en '\033['"${ATTR}m$*"'\033[0m'; }
 
-while read -r local_ref local_oid remote_ref remote_oid
+bold()      { styled_text "1"    "$*"; }
+blue()      { styled_text "94"   "$*"; }
+bold_blue() { styled_text "1;94" "$*"; }
+red()       { styled_text "91"   "$*"; }
+bold_red()  { styled_text "1;91" "$*"; }
+green()     { styled_text "92"   "$*"; }
+
+# shellcheck disable=SC2021 # We want to replace square brackets.
+zero="$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')"
+
+while read -r _ local_oid _ remote_oid
 do
 	if test "$local_oid" = "$zero"
 	then
@@ -43,18 +36,19 @@ do
 		fi
 
 		# Check for version consistency.
-		make version/check
+		make version/check || die "Version check 'make check/version' failed."
+		log "✓ Version check passed."
+
+		CL_FILE="dev/changes/v$(cat dev/VERSION).md"
+		# Check for changelog update.
+		git diff --name-only "$range" | grep -qE "^$CL_FILE\$" || {
+			die "No update to changelog file '$CL_FILE'"
+		}
 
 		# Just run the tests. (TODO: Run then against _commited_ changes only.)
-		make test
+		make test || die "Tests failed."
+		log "✓ Tests passed."
 
-		# Check for WIP commit
-		commit="$(git rev-list -n 1 --grep '^WIP' "$range")"
-		if test -n "$commit"
-		then
-			echo >&2 "Found WIP commit in $local_ref, not pushing"
-			exit 1
-		fi
 	fi
 done
 
