check docs up to date before push

diff --git a/dev/git_hooks/pre-push b/dev/git_hooks/pre-push
--- a/dev/git_hooks/pre-push
+++ b/dev/git_hooks/pre-push
@@ -2,7 +2,7 @@
 
 set -Eeuo pipefail
 
-log() { echo >&2 "==> $*"; }
+log() { echo >&2 "$*"; }
 die() { log "$(bold_red "FATAL: ") $(bold "$*")"; exit 1; }
 
 ok() { log "$(bold_green "OK: $*")"; }
@@ -15,6 +15,31 @@ bold_blue() { styled_text "1;94" "$*"; }
 red()       { styled_text "91"   "$*"; }
 bold_red()  { styled_text "1;91" "$*"; }
 green()     { styled_text "92"   "$*"; }
+
+DIR=".git/hook_tmp/pre-push"
+
+test_in_isolation() {
+	local REF="$1"
+	shift
+	rm -rf "$DIR"
+	mkdir -p "$DIR"
+	git clone . "$DIR"
+	(
+		cd "$DIR"
+		git diff --exit-code || die "Unable to check $1 - unclean clone."
+		git checkout "$REF"
+		git diff --exit-code || die "Unable to check $1 - unclean checkout."
+		"$@" || exit 1
+	) || return 1
+}
+
+assert_no_diff_caused_by() {
+	test_in_isolation "$@"
+	(
+		cd "$DIR"
+		git diff --exit-code || exit 1
+	) || return 1
+}
 
 # shellcheck disable=SC2021 # We want to replace square brackets.
 zero="$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')"
@@ -44,9 +69,14 @@ do
 		git diff --name-only "$range" | grep -qE "^$CL_FILE\$" || {
 			die "No update to changelog file '$CL_FILE'"
 		}
+		log "✓ Changes logged in $CL_FILE"
 
-		# Just run the tests. (TODO: Run then against _commited_ changes only.)
-		make test || die "Tests failed."
+		# Check docs are up-to-date.
+		assert_no_diff_caused_by make docs || die "Docs are stale; please run 'make docs' and commit the changes."
+		log "✓ Docs are up-to-date."
+ 
+		# Check tests pass with commited changes.
+		test_in_isolation  make test || die "Please ensure tests pass on this branch before pushingPlease."
 		log "✓ Tests passed."
 
 	fi
