logging

diff --git a/action-setup b/action-setup
--- a/action-setup
+++ b/action-setup
@@ -2,9 +2,7 @@
 
 set -euo pipefail
 
-echo "DEBUG: env"
-env
-echo "END DEBUG"
+die() { echo "$*"; exit 1; }
 
 # This script exports some environment variables for later steps,
 # and clones this entire repository into the action path.
@@ -40,7 +38,7 @@ echo "DEBUG: ACTION_REF=$ACTION_REF"
 # Clone the repo if needed.
 if [[ ! -d "$ACTION_PATH/.git" ]]; then
 	# Go to the directory containing the directory containing the action.
-	cd "$ACTION_PATH/.." || exit 1
+	cd "$ACTION_PATH/.." || die "Unable to cd to '$ACTION_PATH/..'"
 
 	# Destroy the action from orbit.
 	rm -rf "$ACTION_PATH"
@@ -53,7 +51,7 @@ fi
 # Install the CLI
 #
 
-cd "$ACTION_PATH" || exit 1
+cd "$ACTION_PATH" || die "Unable to cd to '$ACTION_PATH'"
 
 # Ensure that config defined in the usage of this action
 # doesn't impact the build of the action's own CLI.
