verify: remove old step summary code

diff --git a/verify/action.yml b/verify/action.yml
--- a/verify/action.yml
+++ b/verify/action.yml
@@ -81,33 +81,14 @@ runs:
       shell: bash
       run: |
         # Verify the build result (fail workflow if not reproduced correctly: ${{ env.REPRODUCIBLE }})
-        OK=true
-        $RUN_CLI verify -json "$RESULT_FILE" || tee > "$VERIFICATION_RESULT" || OK=false
-        if $OK; then
-          TITLE=":white_check_mark: Success, reproducibility check succeeded."
-          MSG="Success!"
-          CODE=0
+        if $RUN_CLI verify -json "$RESULT_FILE" -o "$VERIFICATION_RESULT"; then
+          echo "Success!"
+        elif ! $REPRODUCIBLE; then
+          echo "Failed; not failing workflow because reproducible was set to report not assert."
         else
-          TITLE=":x: Reproducibility check failed."
-          if $REPRODUCIBLE; then
-            MSG="Failed; not failing workflow because reproducible was set to report not assert."
-            CODE=0
-          else
-            MSG="Failed; failing workflow because reproducible was set to assert."
-            CODE=1
-          fi
+          echo "Failed; failing workflow because reproducible was set to assert."
+          exit 1
         fi
-        # Display reprodubibility result.
-        {
-          echo "## $TITLE"
-          echo "Full output below."
-          echo '```json'
-          cat "$VERIFICATION_RESULT"
-          echo '```'
-        } >> "$GITHUB_STEP_SUMMARY"
-
-        echo "$MSG"
-        exit $CODE
 
     # Store reproducibility report.
     - name: Upload Reproducibility Report
