more robust commit time
- No longer relies on local times with no TZ info, all UTC.

diff --git a/scripts/digest_inputs b/scripts/digest_inputs
--- a/scripts/digest_inputs
+++ b/scripts/digest_inputs
@@ -42,9 +42,8 @@ main() {
 	
 	# Gather contextual info from git.
 
-	set_env PRODUCT_REVISION "$(git rev-parse HEAD)"
-	set_env PRODUCT_REVISION_TIME "$(git show -s --format=%cI "$PRODUCT_REVISION")"
-	set_env PRODUCT_REVISION_TIME_LOCAL "$(cut -d+ -f1 <<< "$PRODUCT_REVISION_TIME")"
+	set_env PRODUCT_REVISION      "$(git rev-parse HEAD)"
+	set_env PRODUCT_REVISION_TIME "$(commit_time_utc "$PRODUCT_REVISION")"
 
 	# Set Go-specific vars.
 
@@ -59,6 +58,31 @@ adjacent_path() { echo "$(dirname "$1")/$2"; }
 
 remove_enterprise_suffix() {
 	echo "${1%-enterprise}"
+}
+
+# is_gnu_date fails with no output if the named program in the path is not GNU date.
+# Otherwise it succeeds and prints the name of the program passed in.
+is_gnu_date() {
+	"$1" -d yesterday > /dev/null 2>&1 || return 1
+	echo "$1"
+}
+
+# We rely on the GNU date program as it can convert the format of arbitrary dates.
+# This function echoes either 'date' or 'gdate' if it's installed as one of those.
+# It exits with an error if GNU date is not found.
+gnu_date_prog() {
+	local ERROR="GNU date not installed."
+	[ "$(uname)" != "Darwin" ] || ERROR+=" On mac? Try 'brew install coreutils'"
+	is_gnu_date date || is_gnu_date gdate || err "$ERROR"
+}
+
+commit_time_utc() {
+	local COMMIT_ID="$1"
+	local T
+	T="$(git show -s --format=%cI "$COMMIT_ID")"
+	local DATE_PROG
+	DATE_PROG="$(gnu_date_prog)" || return 1
+	"$DATE_PROG" --utc --iso-8601=seconds -d "$T"
 }
 
 export_to_github_job() { local NAME="$1"
