fix resuable workflow yaml

diff --git a/.github/workflows/reusable-action-test.yml b/.github/workflows/reusable-action-test.yml
--- a/.github/workflows/reusable-action-test.yml
+++ b/.github/workflows/reusable-action-test.yml
@@ -52,7 +52,9 @@ jobs:
       WHEN: ${{ inputs.when }}
     steps:
       - if: inputs.assert != 'success' && inputs.assert != 'failure'
-        run: echo "assert must be one of: 'success' or 'failure'"; exit 1
+        run: |
+          echo "assert must be one of: 'success' or 'failure'"
+          exit 1
       - uses: actions/checkout@v3
       - name: Invoke actions-go-build when ${{ env.WHEN }}
         id: build
